##Get all orders
GET http://localhost:8083/orders

Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiZW1haWwiOiJ0ZXN0MkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwOCR0Ry5qMTdSeGRRS040R1hXVEZkajZ1U2NqbHJEeExGeXE0UVM3Ny9aWS55VDNQNmNvSHp4YSIsImlhdCI6MTY1ODg5NTEwOCwiZXhwIjoxNjU4OTM4MzA4fQ.C4yZ_-Qu7PdkkXlauTEilYQeyfj0Rw79qTZ5OOwClWY
###

##Create order
POST http://localhost:8083/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiZW1haWwiOiJ0ZXN0MkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwOCR0Ry5qMTdSeGRRS040R1hXVEZkajZ1U2NqbHJEeExGeXE0UVM3Ny9aWS55VDNQNmNvSHp4YSIsImlhdCI6MTY1ODg5NTEwOCwiZXhwIjoxNjU4OTM4MzA4fQ.C4yZ_-Qu7PdkkXlauTEilYQeyfj0Rw79qTZ5OOwClWY
Content-Type: application/json

{
      "customer_id": 444,
      "customer_name":"Success John",
      "items": "[{},{},{},kkjjjjjjjjjjdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffjjjjjjjjpjiffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk{}]",
      "items_count": 4,
      "total": 888.5

##Get order by  Id
GET http://localhost:8083/orders/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQwOCQxd1Zjci5oRHBpODNmTWJWdHV1OVp1RXNnU2xMMUNvWkNLZlowdTliMVNTVE9HLk5QRjdUYSIsInBob25lIjoiKzI1NDExIiwibG9jYXRpb24iOiJLZW5vbCIsImlhdCI6MTY1ODg3MDM2MSwiZXhwIjoxNjU4OTEzNTYxfQ.-YGPqBJxCjmFJxtFEc7aeHMJqlN-NX9FM7oE_8_Xa_M

###

##Get order by  Uid
GET http://localhost:8083/orders/user/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQwOCQxd1Zjci5oRHBpODNmTWJWdHV1OVp1RXNnU2xMMUNvWkNLZlowdTliMVNTVE9HLk5QRjdUYSIsInBob25lIjoiKzI1NDExIiwibG9jYXRpb24iOiJLZW5vbCIsImlhdCI6MTY1ODg3MDM2MSwiZXhwIjoxNjU4OTEzNTYxfQ.-YGPqBJxCjmFJxtFEc7aeHMJqlN-NX9FM7oE_8_Xa_M

###

##Update order
PATCH http://localhost:8083/orders/2002
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQwOCQxd1Zjci5oRHBpODNmTWJWdHV1OVp1RXNnU2xMMUNvWkNLZlowdTliMVNTVE9HLk5QRjdUYSIsInBob25lIjoiKzI1NDExIiwibG9jYXRpb24iOiJLZW5vbCIsImlhdCI6MTY1ODg3MDM2MSwiZXhwIjoxNjU4OTEzNTYxfQ.-YGPqBJxCjmFJxtFEc7aeHMJqlN-NX9FM7oE_8_Xa_M

{
      "items": "[{\"name\":\"john\"},{'name':'test'},{},{}]",
      "items_count": 4,
      "total": 888.5

}
###

##CLEAR order by  Id
PATCH http://localhost:8083/orders/cl/1
###
##Recent orders
GET http://localhost:8083/orders/recent/10
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiZW1haWwiOiJ0ZXN0MkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwOCR0Ry5qMTdSeGRRS040R1hXVEZkajZ1U2NqbHJEeExGeXE0UVM3Ny9aWS55VDNQNmNvSHp4YSIsImlhdCI6MTY1ODY0Mjk1MSwiZXhwIjoxNjU4Njg2MTUxfQ.XG8R4JMjW5buuSzgpUmavZIZh6QdThEhTc6Vqnkk6AM
