##/all/:orderBy/:orderForm
## 1. all products
GET http://localhost:8081/all/price/asc

###

##/pg/:page/:orderBy/:orderForm/:limit
## 2. All products paginated
GET http://localhost:8081/pg/5/price/asc/1

###
##/category/all/:category/:orderby/:orderform
## 3. products by category all
GET http://localhost:8081/category/all/official/price/asc

###
##/category/pg/:category/:page/:orderby/:orderform/:limit
##4. products by category paginated
GET http://localhost:8081/category/pg/outdoor/1/price/asc/10

###
##/:id
## 5. Get product by id
GET http://localhost:8081/1

###
##/:id
## UPDATING PRODUCTS
PATCH http://localhost:8081/1
Content-Type: application/json

{
    "name":"Ankle socks",
    "price":222,
    "image":"https://url/image",
    "description":"testing endpoint",
    "category":"outdoor"
}

###
##/:id
## DELETING PRODUCT
PATCH http://localhost:8081/del/2
###
##/:post
## CREATING PRODUCT
POST http://localhost:8081/post
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiZW1haWwiOiJ0ZXN0MkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwOCR0Ry5qMTdSeGRRS040R1hXVEZkajZ1U2NqbHJEeExGeXE0UVM3Ny9aWS55VDNQNmNvSHp4YSIsImlhdCI6MTY1OTAwMDc3OSwiZXhwIjoxNjU5MDQzOTc5fQ.jR70-2c-twOL3Ctj771Hkekf4bUB96CSDKzFBQhsqrE
Content-Type: application/json

{ 
    "name":"Tshirt",
    "description" : "CHAMPION BASIC JERSEY TEE IN ORIGINAL NAVY",
    "image": " https://cdn.shopify.com/s/files/1/0186/1574/products/KN021051-BL47_2000x.jpg?v=1611104928",
    "price" : "$40",
    "category" : "casual"
    }

###

##/:search/:param
## DELETING PRODUCT
POST http://localhost:8081/search/kiw
###