## 1. SIGN UP
POST http://localhost:8082/signup
Content-Type: application/json

{
    "name":"John",
    "email":"john@gmail.com",
    "password":"Password",
    "phone":"+25411",
    "location":"Kenol"
}
###
## 2. Log In
POST http://localhost:8082/login
Content-Type: application/json

{
    "email":"john@gmail.com",
    "password":"Password"
}
###
## 3. Log Out
PATCH http://localhost:8082/logout
###
## 4. Update
PATCH http://localhost:8082/update/3
Content-Type: application/json

{
    "name":"",
    "email":"",
    "password":"",
    "phone":"",
    "location":""
}
###
## 5. get customer by id
GET http://localhost:8082/id/1
###
## 6. get all customers
GET http://localhost:8082/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQwOCRpMjdHcm0wWnFBVnFkMWlDS2h2aUouVDljY3Jxb1A4MXE0b0dCUW50TXQxQ0hNOURWWjdaZSIsInBob25lIjoiKzI1NDExIiwibG9jYXRpb24iOiJLZW5vbCIsImlhdCI6MTY1ODQwNjcxMywiZXhwIjoxNjU4NDQ5OTEzfQ.bOTy5jFQEr2MdPPw8moRghl9ceH29-4Dh4G47PdAVBg
###
## 7. Delete customer
PATCH http://localhost:8082/delete/5
Content-Type: application/json

{
    "email":"",
    "password":""
}
###