## 1. SIGN UP
POST http://localhost:8082/signup
Content-Type: application/json

{
    "name":"",
    "email":"",
    "password":"",
    "phone":"",
    "location":""
}
###
## 2. Log In
POST http://localhost:8082/login
Content-Type: application/json

{
    "email":"",
    "password":""
}
###
## 3. Log Out
PATCH http://localhost:8082/logout
###
## 4. Update
PATCH http://localhost:8082/update
Content-Type: application/json

{
    "name":"",
    "email":"",
    "password":"",
    "phone":"",
    "location":""
}
###
## 5. get customer by id
GET http://localhost:8082/id/01
###
## 6. get all customers
GET http://localhost:8082/all
###
## 7. Delete customer
PATCH http://localhost:8082/delete
Content-Type: application/json

{
    "email":"",
    "password":""
}
###